Refs #27046 - Resolv the DNS server IP if needed
theforeman/smart_proxy_dns_infoblox pull request #26
Opened 2019-06-26 16:30 UTC by ekohl

This is an alternative implementation to 79ceedcee3bb3e334cea2f7219a8820ae44dc6dd.

The root cause of the issue is that if the DNS server is a hostname, the resolver can't find it because it has no way to get the IP address of the resolver. By using the system resolver (as the HTTP API would), we get equivalent behavior.

A minimal reproducer of what's happening:

```ruby
require 'resolv'
resolver = Resolv::DNS.new(:nameserver => 'infoblox.example.com')
resolver.getresource('host.example.org', Resolv::DNS::Resource::IN::A)
```

2019-06-27 07:20 UTC, lzap commented
This is not alternative to 79ceedc the comment about hostname vs IP in the settings comment was added as extra pre-caution information but it was not culprit of the problem. The real issue is DNS conflict validation which seems easy to implement at first sight (just override `record_conflicts_ip` and `record_conflicts_name`) but it's not that easy (Infoblox have classes for each resource, this must be all implemented, tests, possible breaking change). This is why I was pushing for something really small that will enable customers to use the feature until I get to the proper fix described above.

This patch however won't hurt and I can merge it with few comments.

2019-06-27 07:21 UTC, lzap requested changes

2019-06-27 07:21 UTC, lzap commented on lib/smart_proxy_dns_infoblox/plugin_configuration.rb
> +        Resolv.getaddresses(dns_server).first
This needs to handle errors (timeout, resolv error) and we should error out with a fatal error nicely explaining what just happened.

2019-07-15 12:38 UTC, ekohl commented
https://github.com/theforeman/smart_proxy_dns_infoblox/pull/27 makes this redundant.

2019-07-15 12:38 UTC, closed without merging